### ISSUE TITLE
Adding a cache to Guzzle?

### ISSUE THREAD

**Issue by cjunge-work** [aws/aws-sdk-php#1020]
I wish to add a caching layer to the Guzzle requests, using a Guzzle 6 middleware, but I can't figure out how it would be possible to add it in.

I am using Symfony 2.8, with a manual S3 client service definition. I can't see how I could add middleware to the Guzzle client.

**Comment by cjyclaire** [comment]
@cjunge-work , could you provide more information about what SDK behavior related to this? Are you suggesting configuration of a S3 client with guzzle client handler perhaps? Or you are suggesting some guzzle request feature? 

For guzzle issue not SDK related, you could also open issue at Guzzle repo [here](https://github.com/guzzle/guzzle).

**Comment by cjunge-work** [comment]
The SDK uses Guzzle as the HTTP transport, and I can't seem to find how to alter the middleware that Guzzle uses.

It seems that the Guzzle handler is not exposed by the SDK, and the SDK instantiates the handler itself.

**Comment by cjyclaire** [comment]
@cjunge-work , it's true that SDK doesn't expose the Guzzle handler while provide handler options itself.
> I wish to add a caching layer to the Guzzle requests, using a Guzzle 6 middleware

May I ask more details about this "caching layer" that you are expecting? Then I could try provide some work-arounds there or tag it as a feature request in our backlog. Also we can figure out whether it should be a guzzle feature or a SDK feature to work on.

**Comment by cjunge-work** [comment]
Guzzle already supports adding middleware that can enable caching (or other features). Eg. https://github.com/Kevinrob/guzzle-cache-middleware

To allow adding caching of S3 content it should be a simple case of configuring and adding that middleware to the Guzzle client. But, due to how the SDK instantiates and accesses the client, it is not exposed outside of the SDK, as far as I can see.

Exposing some way of configuring the Guzzle client to add the middleware would be great!

**Comment by cjyclaire** [comment]
Thanks for the information, I'd tag this as a feature request.

**Comment by kkopachev** [comment]
@cjunge-work How about https://github.com/aws/aws-sdk-php/blob/master/src/Sdk.php#L164-L166 and https://github.com/aws/aws-sdk-php/blob/master/src/AwsClient.php#L93-L109 ?

**Comment by cjyclaire** [comment]
@cjunge-work, More information on @kkopachev suggestions, you could probably try [http_handler](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#http-handler) configuration in SDK Client.

**Comment by cjunge-work** [comment]
@kkopachev @cjyclaire that looks like it might solve the issue. I will test and reply back soon.

**Comment by cjunge-work** [comment]
It is possible to add a custom http_handler with the caching enabled. Below is an example Symfony configuration to handle it:

```
csa_guzzle:
    profiler: %kernel.debug%
    logger: %kernel.debug%
    clients:
        aws: ~
    cache:
        enabled: true
        adapter: aws.cache.adaptor

services:
    aws.cache.service:
        class: Doctrine\Common\Cache\FilesystemCache
        public: false
        arguments: ["%kernel.cache_dir%/aws", 3600]
    aws.cache.adaptor:
        class: Test\DoctrineAdapter
        public: false
        arguments: ["@aws.cache.service"]
    http.handler:
        class: Aws\Handler\GuzzleV6\GuzzleHandler
        arguments: ["@csa_guzzle.client.aws"]
    aws.sdk:
        class: Aws\Sdk
        public: false
        arguments:
            -
                credentials:
                   key: "%amazon_s3.key%"
                   secret: "%amazon_s3.secret%"
                region: "%amazon_s3.region%"
                version: '2006-03-01'
                http_handler: "@http.handler"
    s3.client:
        class: Aws\S3\S3Client
        factory: ["@aws.sdk", createS3]
        public: true
```

It's kinda messy, but it works!

Note: I added a custom DoctrineAdaptor that filters out the AWS headers that change between each request (invocation ID, date, authorization).
