### ISSUE TITLE
Pull request #2776 breaks local development when using amazon/amazon-ecs-local-container-endpoints container

### ISSUE THREAD

**Issue by BenHarris** [aws/aws-sdk-php#2825]
### Describe the bug

When using the `amazon/amazon-ecs-local-container-endpoints` docker container for local development, http is used (e.g. **http**://ecs-local-endpoints/role/RoleName). The latest release results in the following error when making calls to AWS, which would have used credentials provided by the ecs local endpoints container:
`Something went wrong" error="Uri 'http://ecs-local-endpoints/role/RoleName' contains an unsupported host."`

[This pull request enforced https](https://github.com/aws/aws-sdk-php/pull/2776/files#diff-df605bd17bbefa819009ae8794c9f62ccef6abd225dc86f8d13f92bfc333f605R187) (`if ($parsed['scheme'] !== 'https') {`) in the `isCompatibleUri($uri)` function, defined in `src/Credentials/EcsCredentialProvider.php`

### Expected Behavior

It should work.

### Current Behavior

`Something went wrong" error="Uri 'http://ecs-local-endpoints/role/RoleName' contains an unsupported host."`

### Reproduction Steps

Set up as per this AWS article: [A Guide to Locally Testing Containers with Amazon ECS Local Endpoints and Docker Compose](https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/)

### Possible Solution

Remove the `if ($parsed['scheme'] !== 'https') {` check.

### SDK version used

3.285.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

Ddocker image: php:8.2-fpm-alpine

**Comment by stobrien89** [comment]
Hi @BenHarris,  

Sorry to hear about the issues.  For right now, I'd recommend pinning your version or updating your host to a loopback address.  This change is ultimately for security purposes and to align with other SDK behavior, but currently working out what we can do to make this backward-compatible.

**Comment by stobrien89** [comment]
Hi @BenHarris,

Thanks for your patience.  Could you tell me whether or not `ecs-local-endpoints` resolves to a loopback address on your machine?

**Comment by BenHarris** [comment]
Hi @stobrien89,

I am using docker compose and the service is called `ecs-local-endpoints`. This is a ping from within the `php` container to the `ecs-local-endpoints` container.
```
/var/www # ping ecs-local-endpoints
PING ecs-local-endpoints (172.18.0.11): 56 data bytes
64 bytes from 172.18.0.11: seq=0 ttl=64 time=0.083 ms
```

I hope this answers your question. If not, please let me know more specifically what you want me to do.

This is the rough makeup of my docker-compose definition.
```
version: "3.8"

services:
    # Vends credentials to the other containers
    ecs-local-endpoints:
        image: amazon/amazon-ecs-local-container-endpoints
        restart: always
        volumes:
            - /var/run:/var/run
            - $HOME/.aws/:/home/.aws/
        environment:
            HOME: "/home"
            AWS_PROFILE: "default"

    # PHP application
    app:
        image: php:8.2-fpm-alpine
        restart: always
        volumes:
            - ./app:/var/www
        depends_on:
            - ecs-local-endpoints
        environment:
            ECS_CONTAINER_METADATA_URI: "http://ecs-local-endpoints/v3"

    # Nginx reverse proxy
    nginx:
        image: nginx:1.25-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
```

Would it be possible to just add an `ALLOW_INSECURE` type environmental variable?
