### ISSUE TITLE
SNS v3

### ISSUE THREAD

**Issue by ajcerqueti** [aws/aws-sdk-php#910]
Can I just check, did SNS break with v3? I migrated away from using the v2 Factory, and tried to configure like I would S3 for example:

```yaml
aws_credentials:
    class: Aws\Credentials\Credentials
    arguments: [%aws_key%, %aws_secret%]

aws_sns:
    class: Aws\Sns\SnsClient
    arguments:
        -
            region: %aws_region%
            version: %aws_sns_version%
            credentials: '@aws_credentials'
     
```

and now none of the commands seem to work:

```
InvalidArgumentException: Operation not found: Publish
```

The SNSClient is pretty much empty other than an annotated list of methods and the basic class

```php
class SnsClient extends AwsClient {}
```

Should I just keep using the Factory method? Is the new style being implemented? Can I help?
