### ISSUE TITLE
Missing required client configuration options: version: (string) 

### ISSUE THREAD

**Issue by PaddyLock** [aws/aws-sdk-php#965]
I am getting the following error when clearing the cache after composer install;

```
    A "version" configuration value is required. Specifying a version constraint      
    ensures that your code will not be affected by a breaking change made to the      
    service. For example, when using Amazon S3, you can lock your API version to      
    "2006-03-01".                                                                     
                                                                                      
    Your build of the SDK has the following version(s) of "s3": * "2006-03-01"        
                                                                                      
    You may provide "latest" to the "version" configuration value to utilize the      
    most recent available API version that your client's API provider can find.       
    Note: Using 'latest' in a production application is not recommended.              
                                                                                      
    A list of available API versions can be found on each client's API documentation  
    page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are        
    unable to load a specific API version, then you may need to update your copy of   
    the SDK.
```

I have the following packages installed

```
"aws/aws-sdk-php-symfony": "~1.0",
"aws/aws-sdk-php": "3.2.6",
```

I am creating my client like this

```
$client = new S3Client(array(
            'region' => $awsS3Region,
            'version' => '2006-03-01',
            'credentials' => array(
                'key' => $awsKey,
                'secret'  => $awsSecret,
              )
        ));
```

And I also have this in my config

```
aws:
    version: latest
    region: us-east-1
    credentials:
        key: '%aws_key%'
        secret: '%aws_secret%'
    S3:
        version: '2006-03-01'

knp_gaufrette:
    adapters:
        amazon:
            aws_s3:
                service_id: aws.s3
                bucket_name: %s3_bucket%
                options:
                    create: true
    filesystems:
        amazonS3:
            adapter: amazon

    stream_wrapper: ~
```
